version: "3.9"

services:
  admanager:
    container_name: admanager-api
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    container_name: admanager-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
